Update all cargo editions to 2021
Beacuse it has implact on compiler behaviour.

WIth the 2021 edition the bellow error doesn't occur:

  error[E0500]: closure requires unique access to `self` but it is already borrowed
     --> cli/examples/language-syms.rs:554:37
      |
  551 | /                 self.merges
  552 | |                     .entry(kind.to_string())
      | |____________________________________________- borrow occurs here
  553 |                       .and_modify(|e| e.push((id, kind.to_string(), name.to_string())))
  554 |                       .or_insert_with(|| {
      |                        -------------- ^^ closure construction occurs here
      |                        |
      |                        first borrow later used by call
  555 |                           vec![
  556 |                               self.origins.remove(kind).unwrap(),
      |                               ------------ second borrow occurs due to use of `self` in closure

  For more information about this error, try `rustc --explain E0500`.